<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9G3E9V2" failures="0" tests="3" name="com.unified.infinity.uitest.admin.Doubts" time="73.290" errors="1" timestamp="2023-01-06T16:47:39 IST" skipped="2">
  <testcase classname="com.unified.infinity.uitest.admin.Doubts" name="DoubtsSigninwithOTP" time="73.290">
    <error message="Test can&#039;t continue, fail here!" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Test can't continue, fail here!
at com.unified.infinity.utils.WebInteractUtil.TearDown(WebInteractUtil.java:171)
at com.unified.infinity.utils.WebInteractUtil.SendKeys(WebInteractUtil.java:40)
at com.unified.infinity.libraries.UnifiedLibrary.DoubtsSigninwithOTP(UnifiedLibrary.java:1667)
at com.unified.infinity.uitest.admin.Doubts.DoubtsSigninwithOTP(Doubts.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- DoubtsSigninwithOTP -->
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.Doubts" name="DoubtsSignUp">
    <skipped/>
  </testcase> <!-- DoubtsSignUp -->
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.Doubts" name="DoubtsLogout">
    <skipped/>
  </testcase> <!-- DoubtsLogout -->
  <system-out/>
</testsuite> <!-- com.unified.infinity.uitest.admin.Doubts -->
